version: 2
models:
  - name: src_shopit_data
    description: Updated table with minimal columns and non-null values in the product column.
    columns:
      - name: order_id
        description: Unique identifier of each order made.
        tests:
          - not_null
      - name: product_id
        description: Unique identifier of each product.
        tests:
          - not_null
      - name: product
        description: product_name.
        tests:
          - not_null
      - name: order_date
        description: Date when the order was made
        tests:
            - dbt_expectations.expect_column_values_to_be_of_type:
                column_type: date